apiVersion: v1
kind: Service
metadata:
  name: static-client
  namespace: $CLIENT_NS
spec:
  selector:
    app: static-client
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
  namespace: $CLIENT_NS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
  namespace: $CLIENT_NS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        consul.hashicorp.com/connect-service-upstreams: "static-server.$SERVER_NS.$PARTITION:8080"
    spec:
      containers:
        - name: static-client
          image: curlimages/curl:latest
          # Just spin & wait forever, we'll use `kubectl exec` to demo
          command: ['/bin/sh', '-c', '--']
          args: ['while true; do sleep 30; done;']
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: static-client
