global:
  name: consul
  image: k3d-registry.localhost:5001/consul-dev
  peering:
    enabled: true
  tls:
    enabled: true
  ui:
    enabled: true
  enterpriseLicense:
    secretName: license
    secretKey: license.txt
    enableLicenseAutoload: true
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "default"
  acls:
    manageSystemACLs: true
connectInject:
  enabled: true
  default: true
meshGateway:
  enabled: true
# Everything below is for k3d
  service:
    type: "NodePort"
    nodePort: "30100"
server:
  resources:
    requests:
      memory: '100Mi'
      cpu: '100m'
    limits:
      memory: '200Mi'
      cpu: '200m'
  extraConfig: |
    {
      "log_level": "TRACE"
    }
#server:
#  exposeGossipAndRPCPorts: "true"
