global:
  name: consul
  image: k3d-registry.localhost:5000/consul-dev
  imageK8S: k3d-registry.localhost:5000/consul-k8s
  #imageK8S: k3d-registry.localhost:5001/consul-control-plane-dev
  peering:
    enabled: true
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key
      secretKey: tls.key
  ui:
    enabled: true
  enterpriseLicense:
    secretName: license
    secretKey: license.txt
    enableLicenseAutoload: true
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "ap1"
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token
      secretKey: token
externalServers:
  enabled: true
  tlsServerName: server.dc1.consul
connectInject:
  enabled: true
  default: true
  consulNamespaces:
    mirroringK8S: true
meshGateway:
  enabled: true
# Everything below is for k3d
  service:
    type: "NodePort"
    nodePort: "30101"
server:
  enabled: false
