global:
  name: consul
  image: "k3d-registry.localhost:5002/consul-dev@sha256:27708036dc0496562b1f9af487f418a5685dc63540eca34f25843b6f7ae69512"
  imageK8S: "k3d-registry.localhost:5002/consul-k8s-control-plane-dev@sha256:0dfce57eee7006709c2e689a39694474b1bb0cfee9a9c9f84aa8b6f2ef9fb029"
  peering:
    enabled: true
  tls:
    enabled: true
  ui:
    enabled: true
  enterpriseLicense:
    secretName: license
    secretKey: license.txt
    enableLicenseAutoload: true
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "default"
  acls:
    manageSystemACLs: true
connectInject:
  enabled: true
  default: true
  consulNamespaces:
    mirroringK8S: true
meshGateway:
  enabled: true
  # Everything below is for k3d
  service:
    type: "NodePort"
    nodePort: "30100"
server:
  extraConfig: |
    {
      "log_level": "TRACE"
    }
  resources:
    requests:
      memory: '100Mi'
      cpu: '100m'
    limits:
      memory: '200Mi'
      cpu: '200m'
#server:
#  exposeGossipAndRPCPorts: "true"
