apiVersion: consul.hashicorp.com/v1alpha1
kind: SamenessGroup
metadata:
  name: mine
spec:
  defaultForFailover: true
  members:
    - partition: default
    - peer: cluster-01-a
    - peer: cluster-01-b
    - peer: cluster-02-a
